### ISSUE TITLE
关于模块内的数据

### ISSUE THREAD

**Issue by ClownQiang** [Meituan-Dianping/Shield#2]
你好，这边我看了项目中的sample，感觉设计非常棒。但是对于view与数据绑定还是有点疑惑，每个单独的模块对应的数据model是不是也要严格定义好，且后端返回的数据类型也要严格参照view内绑定的数据类型。方便的话，建议可以加上有网络获取数据的例子，这样能够更好的了解到在这方面实际应用 :)

**Comment by rskt** [comment]
网络请求并不是Shield框架所关注的重点，实际上可以在Shield模块中对接任意网络请求框架。同样的，也可以在此基础上使用诸如DataBinding等工具来做一些view与数据绑定的工作。目前在这个方面，Shield并没有严格的定义.
附一张Shield框架大致的流程图
![2017-12-22 11 11 00](https://user-images.githubusercontent.com/22768315/34283925-6cbe1c84-e709-11e7-80c0-01d0cc661101.png)
