### ISSUE TITLE
文档更丰富详细点就好啦

### ISSUE THREAD

**Issue by snowberry001** [Meituan-Dianping/Shield#3]
希望shield不仅仅是一个kpi项目

**Comment by rskt** [comment]
文档这块我们会陆续更新到Wiki里，给大家更多的参考，感谢关注我们的开源项目。

**Comment by pingf** [comment]
好久没更新了，所以是kpi项目吧？

**Comment by rskt** [comment]
Shield在美团内部持续迭代和更新中，支撑了多个BG业务。目前团队开发重心是基于Shield开发动态化能力（ReactNative等）。由于团队人力问题，开源项目的更新频率较慢，但绝不是KPI项目。
